# Generated by Django 5.2.17 on 2026-09-21 12:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('unit_cost_base', models.DecimalField(decimal_places=4, max_digits=15)),
                ('initial_quantity_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batches', to='catalogue.product')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='administration.storagelocation')),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_quantity_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('counted_quantity_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variance_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_adjustments_authorized', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adjustments', to='inventory.batch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
            ],
            options={
                'db_table': 'stock_adjustments',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('quantity_reserved_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='inventory.batch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='catalogue.product')),
            ],
            options={
                'db_table': 'stock_balances',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(max_length=50)),
                ('quantity_change_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.UUIDField()),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_cost_snapshot', models.DecimalField(decimal_places=4, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movements', to='inventory.batch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_movements_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_number'], name='batches_batch_n_62e6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='batches_expiry__d11ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='batches_status_9b1a8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('branch', 'product', 'batch_number')},
        ),
        migrations.AlterUniqueTogether(
            name='stockbalance',
            unique_together={('branch', 'product', 'batch')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='stock_movem_movemen_d922c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_movem_referen_a0d8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='stock_movem_created_07bdcc_idx'),
        ),
    ]
