# Generated by Django 5.2.17 on 2026-09-21 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(max_length=255)),
                ('tax_identification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('headquarters_address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('currency_code', models.CharField(default='GHS', max_length=10)),
                ('logo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('premises_license_number', models.CharField(max_length=100)),
                ('superintendent_name', models.CharField(max_length=255)),
                ('superintendent_pcn_number', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_central', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='administration.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('DISPENSARY_SHELF', 'Front Counter Dispensary Shelves'), ('COLD_CHAIN_FRIDGE', 'Cold Chain Medical Refrigerator (2-8°C)'), ('BULK_WAREHOUSE', 'Central Bulk Warehouse Bay'), ('QUARANTINE_BAY', 'Quarantine & Regulatory Isolation Bay')], default='DISPENSARY_SHELF', max_length=50)),
                ('temperature_range', models.CharField(default='AMBIENT_15_25C', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='administration.branch')),
            ],
            options={
                'unique_together': {('branch', 'code')},
            },
        ),
    ]
