# Generated by Django 5.2.17 on 2026-09-21 12:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('current_credit_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['customer_code'], name='customers_custome_fdedee_idx'), models.Index(fields=['name'], name='customers_name_25d5e3_idx'), models.Index(fields=['phone'], name='customers_phone_91048b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('payment_terms_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='administration.organization')),
            ],
            options={
                'db_table': 'suppliers',
                'indexes': [models.Index(fields=['code'], name='suppliers_code_e95fc6_idx'), models.Index(fields=['name'], name='suppliers_name_ed482a_idx')],
            },
        ),
    ]
