# Generated by Django 5.2.17 on 2026-09-21 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_role', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=100)),
                ('target_identifier', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('payload_before', models.JSONField(blank=True, null=True)),
                ('payload_after', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
