# Generated by Django 5.2.17 on 2026-09-21 13:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'expense_categories',
            },
        ),
        migrations.CreateModel(
            name='BusinessLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_name', models.CharField(max_length=255)),
                ('principal_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_repayable_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_repaid_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
            ],
            options={
                'db_table': 'business_loans',
            },
        ),
        migrations.CreateModel(
            name='DailyCashUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cash_up_date', models.DateField()),
                ('opening_float', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_cash_sales', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('total_card_sales', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('total_transfer_sales', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('total_expenses_cash', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('expected_cash_in_drawer', models.DecimalField(decimal_places=4, max_digits=15)),
                ('actual_counted_cash', models.DecimalField(decimal_places=4, max_digits=15)),
                ('cash_variance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('status', models.CharField(default='BALANCED', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('reconciled_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cash_ups_reconciled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_cash_ups',
                'unique_together': {('branch', 'cash_up_date')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('payment_method', models.CharField(default='CASH', max_length=50)),
                ('disbursed_to', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('receipt_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='expenses', to='finance.expensecategory')),
            ],
            options={
                'db_table': 'expenses',
                'indexes': [models.Index(fields=['voucher_number'], name='expenses_voucher_ae197b_idx'), models.Index(fields=['created_at'], name='expenses_created_753bda_idx')],
            },
        ),
    ]
