# Generated by Django 5.2.17 on 2026-09-21 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Pharmacy Admin', 'Pharmacy Admin'), ('Pharmacist', 'Pharmacist'), ('Cashier', 'Cashier'), ('Stock Officer', 'Stock Officer'), ('Procurement Officer', 'Procurement Officer'), ('Accountant', 'Accountant'), ('Auditor', 'Auditor'), ('Manager', 'Manager')], default='Pharmacist', max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=True)),
                ('is_temporary_password', models.BooleanField(default=True)),
                ('password_reset_notice', models.JSONField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='administration.branch')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permission_matrix', models.JSONField(default=dict)),
                ('role_sensitive_controls', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='administration.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('max_refund_limit', models.DecimalField(decimal_places=4, default=100.0, max_digits=15)),
                ('stock_adjustment_limit', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('expense_approval_limit', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('po_approval_limit', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('require_two_factor', models.BooleanField(default=False)),
                ('can_override_price', models.BooleanField(default=False)),
                ('can_view_cost_prices', models.BooleanField(default=False)),
                ('can_view_profits', models.BooleanField(default=False)),
                ('sessions_active', models.IntegerField(default=0)),
                ('last_password_change', models.DateTimeField(auto_now_add=True)),
                ('custom_permissions', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
