# Generated by Django 5.2.17 on 2026-09-21 12:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('default_base_unit', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dosage_forms',
            },
        ),
        migrations.CreateModel(
            name='DosagePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('instruction', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dosage_presets',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'units_of_measure',
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
            ],
            options={
                'db_table': 'import_jobs',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('base_dispensing_unit', models.CharField(default='Piece', max_length=50)),
                ('strip_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('pack_box_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('cost_price_base', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('selling_price_base', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('reorder_level_base', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=12)),
                ('maximum_stock_base', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('is_prescription_required', models.BooleanField(default=False)),
                ('is_controlled_substance', models.BooleanField(default=False)),
                ('storage_condition', models.CharField(default='Ambient 15-25°C', max_length=100)),
                ('pregnancy_category', models.CharField(default='B', max_length=10)),
                ('max_daily_dose', models.CharField(blank=True, max_length=100, null=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalogue.category')),
                ('dosage_form', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalogue.dosageform')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductPackagingUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier_name', models.CharField(max_length=50)),
                ('unit_label', models.CharField(max_length=50)),
                ('multiplier_to_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('retail_selling_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('is_dispensable', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_units', to='catalogue.product')),
            ],
            options={
                'db_table': 'product_packaging_units',
            },
        ),
        migrations.CreateModel(
            name='StockAlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_days_to_expiry', models.IntegerField(default=90)),
                ('critical_stock_threshold', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10)),
                ('action_required', models.CharField(default='REORDER', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='catalogue.product')),
            ],
            options={
                'db_table': 'stock_alert_rules',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='products_product_15b636_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand_name'], name='products_brand_n_a8dacd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['generic_name'], name='products_generic_d5a71e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='products_barcode_d008ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productpackagingunit',
            unique_together={('product', 'tier_name')},
        ),
    ]
