# Generated by Django 5.2.17 on 2026-09-21 13:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('inventory', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_number', models.CharField(max_length=50, unique=True)),
                ('opening_float', models.DecimalField(decimal_places=4, max_digits=15)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=50)),
                ('closing_counted_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('closing_system_expected_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('discrepancy_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('reconciliation_notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_shifts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cash_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_shifts',
            },
        ),
        migrations.CreateModel(
            name='DraftSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cart_payload', models.JSONField()),
                ('status', models.CharField(default='HELD', max_length=50)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'draft_sales',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('sale_type', models.CharField(default='RETAIL', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_cost_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('gross_profit_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
                ('is_credit_sale', models.BooleanField(default=False)),
                ('credit_due_date', models.DateField(blank=True, null=True)),
                ('credit_amount_paid', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('prescribing_doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_prescription_number', models.CharField(blank=True, max_length=100, null=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('cash_shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to='sales.cashshift')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_processed', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='parties.customer')),
                ('pharmacist_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=4, max_digits=15)),
                ('payment_method', models.CharField(max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit_payments', to='parties.customer')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_payments', to='sales.sale')),
            ],
            options={
                'db_table': 'credit_payments',
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packaging_unit_name', models.CharField(max_length=50)),
                ('multiplier_to_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_dispensed_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_quantity_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_selling_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_cost_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_line_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_line_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_line_profit', models.DecimalField(decimal_places=4, max_digits=15)),
                ('dosage_instructions', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sale_lines', to='inventory.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sale_lines', to='catalogue.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale')),
            ],
            options={
                'db_table': 'sale_lines',
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('refund_method', models.CharField(max_length=50)),
                ('total_refund_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('return_reason', models.CharField(max_length=255)),
                ('is_restocked_to_inventory', models.BooleanField(default=True)),
                ('condition_assessment', models.CharField(default='INTACT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='returns', to='sales.sale')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sale_returns',
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=50, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('remaining_balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='administration.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='parties.customer')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit_notes_issued', to=settings.AUTH_USER_MODEL)),
                ('original_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale')),
                ('sale_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salereturn')),
            ],
            options={
                'db_table': 'customer_credit_notes',
            },
        ),
        migrations.CreateModel(
            name='SaleTender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tender_method', models.CharField(max_length=50)),
                ('amount_tendered', models.DecimalField(decimal_places=4, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=4, max_digits=15)),
                ('change_given', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('tender_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='sales.sale')),
            ],
            options={
                'db_table': 'sale_tenders',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['receipt_number'], name='sales_receipt_d1cdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sales_created_dbdf91_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sales_status_a83c6f_idx'),
        ),
    ]
